const { build } = require("esbuild");

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/
`;

const isProd = process.env.BUILD === "production";

(async () => {
  try {
    await build({
      entryPoints: ["src/index.ts"],
      bundle: true,
      watch: !isProd,
      platform: "browser",
      external: ["obsidian"],
      format: "cjs",
      mainFields: ["browser", "module", "main"],
      banner: { js: banner },
      sourcemap: isProd ? false : "inline",
      minify: isProd,
      define: {
        "process.env.NODE_ENV": JSON.stringify(process.env.BUILD),
      },
      outfile: "lib/index.js",
    });
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
