/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source visit the plugins github repository
*/

var r=Object.create;var p=Object.defineProperty;var t=Object.getOwnPropertyDescriptor;var a=Object.getOwnPropertyNames;var d=Object.getPrototypeOf,l=Object.prototype.hasOwnProperty;var e=i=>p(i,"__esModule",{value:!0});var u=(i,n)=>{e(i);for(var o in n)p(i,o,{get:n[o],enumerable:!0})},c=(i,n,o)=>{if(n&&typeof n=="object"||typeof n=="function")for(let s of a(n))!l.call(i,s)&&s!=="default"&&p(i,s,{get:()=>n[s],enumerable:!(o=t(n,s))||o.enumerable});return i},g=i=>c(e(p(i!=null?r(d(i)):{},"default",i&&i.__esModule&&"default"in i?{get:()=>i.default,enumerable:!0}:{value:i,enumerable:!0})),i);u(exports,{getApi:()=>P,isPluginEnabled:()=>b});var m=g(require("obsidian")),P=i=>{var n;return i?(n=i.app.plugins.plugins["obsidian-icon-shortcodes"])==null?void 0:n.api:window.IconSCAPIv0},b=i=>i.app.plugins.enabledPlugins.has("obsidian-icon-shortcodes");
